main/urls.py
from django.urls import path
from main import views
app_name = 'authapp'
urlpatterns = [
    path('',views.Home,name="Home"),
    path('signup',views.signup,name="signup"),
    path('login',views.handlelogin,name="handlelogin"),
    path('logout',views.handleLogout,name="handleLogout"),
    path('join',views.enroll,name="enroll"),
    path('profile',views.profile,name="profile"),
    path('contact',views.contact,name="contact"),
    path('gallery',views.gallery,name="gallery"),
    path('attendance',views.attendance,name="attendance"),
     path('services',views.services,name="services"),
    path('blog',views.post_list,name='blog'),
    path('shop',views.shop,name='shop'),
    path('about',views.about,name='about'),
    path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('fetch_data',views.fetch_data,name="fetch_data")

    
    
]

talekarhub/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from distutils.command.upload import upload

from django.contrib.auth.models import User

# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=25)
    email=models.EmailField()
    phonenumber=models.CharField(max_length=12)
    description=models.TextField()

    def __str__(self):
        return self.email

class Enrollment(models.Model):        
    FullName=models.CharField(max_length=25)
    Email=models.EmailField()
    Gender=models.CharField(max_length=25)
    PhoneNumber=models.CharField(max_length=12)
    DOB=models.CharField(max_length=50)
    SelectMembershipplan=models.CharField(max_length=200)
    SelectTrainer=models.CharField(max_length=55)
    Reference=models.CharField(max_length=55)
    Address=models.TextField()
    paymentStatus=models.CharField(max_length=55,blank=True,null=True)
    Price=models.IntegerField(max_length=55,blank=True,null=True)
    DueDate=models.DateTimeField(blank=True,null=True)
    timeStamp=models.DateTimeField(auto_now_add=True,blank=True,)

    def __str__(self):
        return self.FullName

class Trainer(models.Model):
    name=models.CharField(max_length=55)
    gender=models.CharField(max_length=25)
    phone=models.CharField(max_length=25)
    salary=models.IntegerField(max_length=25)
    timeStamp=models.DateTimeField(auto_now_add=True,blank=True)
    img_link = models.FileField(upload_to='media/trainer',null=True)
    desc=models.TextField(null=True)
    facebook_link=models.URLField(null=True,blank=True)
    instagram_link=models.URLField(null=True,blank=True)
    def __str__(self):
        return self.name

class MembershipPlan(models.Model):
    plan=models.CharField(max_length=185)
    price=models.IntegerField(max_length=55)

    def __int__(self):
        return self.id


class Gallery(models.Model):
    title=models.CharField(max_length=100)
    img=models.ImageField(upload_to='gallery')
    timeStamp=models.DateTimeField(auto_now_add=True,blank=True)
    def __int__(self):
        return self.id


class Attendance(models.Model):
    Selectdate=models.DateTimeField(auto_now_add=True)
    phonenumber=models.CharField(max_length=15)
    Login=models.CharField(max_length=200)
    Logout=models.CharField(max_length=200)
    SelectWorkout=models.CharField(max_length=200)
    TrainedBy=models.CharField(max_length=200)
    def __int__(self):
        return self.id



class Service(models.Model):
    name = models.CharField(max_length=30)
    img_link = models.FileField(upload_to='media/service_images')
    description = models.TextField(null=True, blank=True)
    link=models.URLField(null=True,blank=True)


class Post(models.Model):
    title = models.CharField(max_length=255)
    img_link = models.FileField(upload_to='media/blog',blank=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    

class Product(models.Model):
    img_link = models.FileField(upload_to='media/shop',blank=True)
    name = models.CharField(max_length=30)
    desc = models.TextField()
    price = models.IntegerField(default=0)

class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_created=True, auto_now_add=True)
    status = models.BooleanField(default=False)
    address = models.TextField()

templates/about.html
{% extends 'base.html' %} 
{% load static %}
{% block title %} About {% endblock title%}

{% block head %}


    <img src="static/logo/edit_logo.png" alt="Your Logo" style="max-width: 80%; height: auto ;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 80vh;
    margin: 0;;">
    <h1>Talekar Fitness Hub</h1>

</div>

{% endblock head %}
{% block body %}
<style>
    .img-fluid-change{
      height: 10rem;
      width: 7rem;
    }
    
  </style>
  

    <div class="text-center">
        <h2 style="color: black">About us</h2>
    
    <div class="row portfolio-container text-center mt-5" data-aos="fade-up" data-aos-delay="200">
        <div  class="section-title">
        <h2>Team</h2>
        <p>Check our Team</p>
        
     
      </div>

      {% for trainer in trainers %}

      <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
        <div class="member" data-aos="fade-up" data-aos-delay="100">
          <div class="member-img">
            <img src="{{ site_url }}{{ trainer.img_link }}" class="img-fluid" alt="">
            <div class="social">
              <a href=""><i class="bi bi-twitter"></i></a>
              <a href="{{ trainer.facebook_link }}"><i class="bi bi-facebook"></i></a>
              <a href="{{ trainer.instagram_link }}"><i class="bi bi-instagram"></i></a>
              <a href=""><i class="bi bi-linkedin"></i></a>
            </div>
          </div>
          <div class="member-info">
            <h4>{{ trainer.name}}</h4>
            <span>{{ trainer.desc}}</span>
          </div>
        </div>
      </div>
        
        {% endfor %}
    </div>
    </div> 


   


</div>  



{% endblock body %}

templates/attendance.html
{% extends 'base.html' %} 
{% block title %} Attendance {% endblock title%}
{% block head %}

<h1>Apply Attendance</h1>
    

<div class="container mt-2">
  <div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-6">
      {% for message in messages %}
      <div
        class="alert alert-{{message.tags}} alert-dismissible fade show"
        role="alert"
      >
        <strong></strong> {{message}}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %} {% comment %} Contact Us COde {% endcomment %}

      <form action="/attendance" method="post">{% csrf_token %}
        {% csrf_token %}


        <div class="form-group">
            <input
              type="number"
              class="form-control mt-2"
              value="{{user.username}}"
              name="PhoneNumber"
              placeholder="Enter Your Number"
              readonly
              required
            />
          </div>


        <div class="form-group">

          <select class="form-control mt-2" id="workout" name="workout" required>
            <option selected>Select Workout</option>
            <option value="Biceps">Biceps</option>
            <option value="Triceps">Triceps</option>
            <option value="Shoulders">Shoulders</option>
            <option value="Chest">Chest</option>
            <option value="ABS">ABS</option>
            <option value="Back">Back</option>
            <option value="Warm Up">Warm Up</option>
            <option value="Treadmill">Treadmill</option>
          </select>
        </div>

       
          
        <div class="form-group">
            <label for="logintime" class="text-white">Log In</label>
          <input
            type="time"
            class="form-control mt-2"
            name="logintime"
            id="logintime"
            placeholder="Login Time"
            required
          />
        </div>

        <div class="form-group">
            <label for="loginout" class="text-white">Log Out</label>
          <input
            type="time"
            class="form-control mt-2"
            name="loginout"
            id="loginout"
            placeholder="Login Out"
            required
          />
        </div>


        <div class="form-group">
           
                     <select  class="form-control mt-2" id="trainer" name="trainer"  required>
                     <option selected> Select Trainer </option>
                          {% for  p in SelectTrainer %}
                          

<option value="{{p.name}}">{{p.name}}</option>
{% endfor %}

</select>
                


            </div>

                                           


        <br />
        <div class="d-grid gap-2">
          <button class="btn btn-warning" type="submit">Apply Attendance</button>
        </div>
      </form>
    </div>

    <div class="col-md-3"></div>
  </div>
</div>

{% endblock head %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title> Talekar Fitness - {% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">




  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="static/assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="static/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="static/assets/css/style.css" rel="stylesheet">

 
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-lg-between">

      <h1 class="logo me-auto me-lg-0"><a href="/">Talekar Hub<span>.</span></a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto me-lg-0"><img src="static/assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="nav-link scrollto active" href="/">Home</a></li>
          <li><a class="nav-link scrollto" href="/about">About</a></li>
          <li><a class="nav-link scrollto" href="/services">Services</a></li>
          <li><a class="nav-link scrollto " href="/gallery">Gallery</a></li>
          <li><a class="nav-link scrollto" href="/contact">Contact</a></li>
          <li><a class="nav-link scrollto" href="/blog">Blog</a></li>
          <li><a class="nav-link scrollto" href="/shop">Shop</a></li>
          <li class="dropdown"><a href="#"><span>Memberships</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="/join">Enroll</a></li>
             
              <li><a href="/attendance">Attendance</a></li>
        
              <li><a href="/profile">View Profile</a></li>
            </ul>
          </li>
          {% if not request.user.is_authenticated %}
          <li><a class="nav-link scrollto" href="/signup">Register</a></li>
          <li><a class="nav-link scrollto" href="/login">Login</a></li>

          {% else %}
         <li><a class="nav-link scrollto" href="/logout">Logout</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

      
      <a href="/post_blog" class="get-started-btn scrollto">Post The Blog <a>
      

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center justify-content-center">
    <div class="container" data-aos="fade-up">

      <div class="row justify-content-center" data-aos="fade-up" data-aos-delay="150">
        <div class="col-xl-6 col-lg-8">
         

{% block head %}


{% endblock head %}


        </div>
      </div>

     

    </div>
  </section><!-- End Hero -->

  <main id="main">
    {% block body %}
    
    
    
    
    {% endblock body %}
  </main>

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="static/assets/vendor/purecounter/purecounter_vanilla.js"></script>
  <script src="static/assets/vendor/aos/aos.js"></script>
  <script src="static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="static/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="static/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="static/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="static/assets/js/main.js"></script>

</body>

</html>

templates/contact.html
{% extends 'base.html' %}
{% block title %}
Contact Us
{% endblock title %}
{% block head %}

<h1>Contact Us</h1>


<div class="container mt-2">

    <div class="row">
    
    <div class="col-md-3"> </div>
    
    <div class="col-md-6">

    {% if meassages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
      <strong></strong> {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
        {% endif %}

    {% comment %} Contact Us COde  {% endcomment %}

    <form action="/contact" method="post">{% csrf_token %}


        <div class="form-group">
        <input type="text" class="form-control" name="fullname" placeholder="Enter Your Name" required>
        </div>
        
        
        <div class="form-group">
        <input type="email" class="form-control mt-2" name="email" placeholder="Enter Your Email" required>
        </div>
        
        <div class="form-group">
        <input type="number" class="form-control mt-2" name="num" placeholder="Enter Your Number" required>
        </div>
        
        <div class="form-group">
        <label for="desc" class="text-warning">How can i help you?</label>
        <textarea class="form-control mt-2" name="desc" cols="5" rows="3" id="desc"></textarea>
        </div>
        
        
        <br>
        <div class="d-grid gap-2">
          <button class="btn btn-warning" type="submit">Submit</button>
        
        </div>
        
        </form>
        
    
    
    </div>
    
    <div class="col-md-3"></div>
    
    </div>
    
    
    
    </div>




{% endblock head %}

templates/enroll.html
{% extends 'base.html' %} 
{% block title %} Enrollment for Gym {% endblock title%}
{% block head %}

<h1>Join The Best Gym In Muktainagar</h1>
  

<div class="container mt-2">
  <div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-6">
      {% for message in messages %}
      <div
        class="alert alert-{{message.tags}} alert-dismissible fade show"
        role="alert"
      >
        <strong></strong> {{message}}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %} {% comment %} Contact Us COde {% endcomment %}

      <form action="/join" method="post">{% csrf_token %}
        {% csrf_token %}

        <div class="form-group">
          <input
            type="text"
            class="form-control"
            name="FullName"
            placeholder="Enter Your Full Name"
            required
          />
        </div>

        <div class="form-group">
          <input
            type="email"
            class="form-control mt-2"
            value="{{user.email}}"
            name="email"
            placeholder="Enter Your Email"
            readonly
            required
          />
        </div>

        <div class="form-group">

          <select class="form-control mt-2" id="gender" name="gender" required>
            <option selected>Select Gender</option>
            <option value="Male">Male</option>
            <option value="Female">Female</option>
          </select>
        </div>

        <div class="form-group">
          <input
            type="number"
            class="form-control mt-2"
            value="{{user.username}}"
            name="PhoneNumber"
            placeholder="Enter Your Number"
            readonly
            required
          />
        </div>

        <div class="form-group">
          <input
            type="date"
            class="form-control mt-2"
            name="DOB"
            placeholder="Date Of Birth"
            required
          />
        </div>


        <div class="form-group">
           
                     <select  class="form-control mt-2" id="member" name="member"  required>
                     <option selected>Select Membership Plan</option>
                          {% for  p in Membership %}
                          

<option value="{{p.plan}} - {{p.price}}">{{p.plan}} - {{p.price}} Rs</option>
{% endfor %}

</select>
                


            </div>
        <div class="form-group">
           
                     <select  class="form-control mt-2" id="trainer" name="trainer"  required>
                     <option selected> Select Trainer </option>
                          {% for  p in SelectTrainer %}
                          

<option value="{{p.name}}">{{p.name}}</option>
{% endfor %}

</select>
                


            </div>

            <div class="form-group">
                <input
                  type="text"
                  class="form-control mt-2"
                  name="reference"
                  placeholder="Refered By"
                  
                />
              </div>

            <div class="form-group">
                <input
                  type="text"
                  class="form-control mt-2"
                  name="address"
                  placeholder="Address"
                  
                />
              </div>

                                                      


        <br />
        <div class="d-grid gap-2">
          <button class="btn btn-warning" type="submit">Enroll</button>
        </div>
      </form>
    </div>

    <div class="col-md-3"></div>
  </div>
</div>


{% endblock head %}
{% block body %}



{% endblock body %}

templates/fetch_data.html
{% extends 'base.html' %}
{% block title %}
Fetch
{% endblock title %}
{% block head %}
  <div class="text-center">
    <h1>Records </h1>
  </div>
{% endblock head %}
{% block body %}
<div class="container mt-5">
    <h1>Last login Member Data </h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        
        <th scope="col">UserEmail</th>
        <th scope="col">login Time</th>
        <th scope="col">Date Join</th>
       

      </tr>
    </thead>
    <tbody>
        {% for user in last_five_user_data %}
      <tr>
        <th scope="row">{{ user.id }}</th>
       
        <td>{{ user.email }}</td>
        <td>{{ user.last_login }}</td>
        <td>{{ user.date_joined }}</td>

      </tr>
      {% endfor %}
      
    </tbody>
  </table>
  
  
  
</div>
{% comment %} <div class="container mt-5">
    <h1>Trainer Book By User</h1>

  <table class="table">
     <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        
        <th scope="col">UserEmail</th>
        <th scope="col">login Time</th>
        <th scope="col">Date Join</th>
       

      </tr>
    </thead>
    <tbody>
        {% for user in last_five_user_data %}
       <tr>
        <th scope="row">{{ user.id }}</th>
       
        <td>{{ user.email }}</td>
        <td>{{ user.last_login }}</td>
        <td>{{ user.date_joined }}</td>

      </tr>  
      <li>
        <strong>User:</strong> {{ enrollment.FullName }} - {{ enrollment.Email }}<br>
        <strong>Trainer:</strong> {{ enrollment.SelectTrainer.name }} - {{ enrollment.SelectTrainer.phone }}
    </li>
      {% endfor %}
      
    </tbody>
  </table>
  
  
  
</div> {% endcomment %}





{% endblock body %}

templates/gallery.html
{% extends 'base.html' %}
{% block title %}
Gallery
{% endblock title %}
{% block body %}

<div class="container mt-2">
<Center><h1>Gallery</h1></Center>
<div class="row">


{% for post in posts  %}  
<div class="col-md-4">


    <div class="card">
        <img src="{{post.img.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{post.title}}</h5>
          <p class="card-text">Uploaded On : {{post.timeStamp}} </p>
        </div>
      </div>


</div>
{% endfor %}
<br>
<br>


</div>
</div>





{% endblock body %}

templates/payment.html
<!-- payment.html -->

<!DOCTYPE html>
<html>
<head>
    <title>Razorpay Payment</title>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
</head>
<body>

    <button id="rzp-button1">Pay with Razorpay</button>

    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script>
        var options = {
            "key": "rzp_test_PL6TC1CmHX0BfJ",
            "amount": {{ product.price }}, // Amount in paise (e.g., 50 INR)
            "currency": "INR",
            "name": "TALEKAR HUB",
            "description": "{{ product.desc }}",
           "order_id": "{{ order.id }}",
            "handler": function (response){
                // Handle the response data, e.g., redirect to a Django view
                $.post("/payment-success/", {order_id: `{{ order_obj.id }}`, payment_id: response.razorpay_payment_id}, function(data) {
                // Redirect to the success page or perform other actions
                window.location.href = "/payment-success/";
            });
            },
            "prefill": {
                "name": "{{ request.user.first_name }} {{ request.user.last_name }}",
                "email": "{{ request.user.email }}",
                "contact": "{{ request.user.username }}"
            },
            "notes": {
                "address": "{{ order_obj.address }}"
            },
            "theme": {
                "color": "#3399cc"
            }
        };

        var rzp1 = new Razorpay(options);
        rzp1.open();
<!--        document.getElementById('rzp-button1').onclick = function(){-->
<!--            rzp1.open();-->
<!--        };-->
    </script>

</body>
</html>

templates/post_blog.html
{% extends 'base.html' %}
{% block title %}
Blog
{% endblock title %}
{% block head %}
{% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
      <strong></strong> {{message}}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
{% endblock head %}
{% block body %}


<div class="container mt-2 col-md-4">
    <h1>Create a New Blog Post</h1>
    <form method="post" action="{% url 'authapp:post_blog' %}" enctype="multipart/form-data">
        {% csrf_token %}
        
       

        
            <div class="form-group mt-5 ">
              <label for="id_title">Title : </label>
              <input type="text" class="form-control" id="id_title" name="title" aria-describedby="texthelp" placeholder="Enter the Titile : ">
              
            </div>
            {% comment %} <div class="form-group mt-5">
              <label for="id_author">Author</label>
              <input type="text" class="form-control" id="id_author" name="author" placeholder="Enter Author Name: ">
            </div> {% endcomment %}
            <div class="form-group mt-5">
                <label for="id_content">Content : </label>
                <input type="text" class="form-control" id="id_content" name="content" placeholder="Enter Content : ">
            </div>
            <div class="form-group mt-5">
                <label for="id_image">Images</label>
                <input type="file" id="id_image" name="image"  accept="image/*">
            </div>
           
            <button type="submit" class="btn btn-primary mt-5">Submit</button>
        
    </form>


<br>
<br>



</div>





{% endblock body %}

templates/profile.html
{% extends 'base.html' %}
{% block title %}
Profile
{% endblock title %}
{% block body %}




<div class="container">

    <div class="row">
    
    <div class="col-md-4">
      
    <h1>Enrollment Details</h1>
    {% comment %} Contact Us COde  {% endcomment %}
    {% for post in posts %}
    
   
    <ul class="list-group">
        <li class="list-group-item bg-warning text-dark"><h5>Name : {{post.FullName}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Email : {{post.Email}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Gender : {{post.Gender}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>PhoneNumber : {{post.PhoneNumber}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>DOB : {{post.DOB}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Membership plan : {{post.SelectMembershipplan}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Trainer : {{post.SelectTrainer}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Reference : {{post.Reference}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Address : {{post.Address}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Payment Status : {{post.paymentStatus}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Amount Paid : {{post.Price}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Upcoming Due Date : {{post.DueDate}}</h5></li>
        <li class="list-group-item bg-warning text-dark"><h5>Joining date : {{post.timeStamp}}</h5></li>
      
       
      </ul>
      {% endfor %}
    
    
    
    
    </div>
    
    <div class="col-md-8">


      <div><Center><h2 class="display-4 mt-3"><b>Attendance Data</b></h2></Center></div>

  
      
      <table class="table">
        <thead class="thead-warning">
          <tr>
          
            <th scope="col">Date</th>
            <th scope="col">Login</th>
            <th scope="col">Logout</th>
            <th scope="col">Workout</th>
            <th scope="col">Trained By</th>
          </tr>
        </thead>
        <tbody>

          {% for attend in attendance %}
          <tr>
            
            <td>{{attend.Selectdate}}</td>
            <td>{{attend.Login}}</td>
            <td>{{attend.Logout}}</td>
            <td>{{attend.SelectWorkout}}</td>
            <td>{{attend.TrainedBy}}</td>
            
           
         
            
           
          </tr>
          {% endfor %}
        
        </tbody>
      </table>
    
    
    </div>
    
    
    
    
    
    </div>




{% endblock body %}

templates/shop.html
{% extends 'base.html' %}
{% block title %}
Shop
{% endblock title %}
{% block head %}
  <div class="text-center">
    <h1>Buy The Trusted Product </h1>
  </div>
{% endblock head %}
{% block body %}
<style>
    .img-fluid-shop{
      height: 10rem;
      width: 7rem;
      margin:auto;
    }
    
  </style>
  

<div class="container">
    <div class="container mt-5">
        <div class="row">
            {% for product in products %}
    <div class="col-md-4 mb-4">
        <div class="card">
            <img src="{{ site_url }}{{ product.img_link }}" class="card-img-top img-fluid-shop" alt="{{ product.name }}">
            <div class="card-body">
                <h5 class="card-title fw-bold">{{ product.name }}</h5>
                <p class="card-text">{{ product.desc }}</p>
                <p class="card-text fw-bold">/- {{ product.price  }}</p>
                <div class="container">
                    <div class="row">
                        <div class="col-md-12 d-flex justify-content-center text-center">
                            <a href="{% url 'authapp:initiate_payment' %}?product_id={{ product.id }}" class="btn btn-primary col-md-2">Buy</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}
            <!-- Repeat similar card structures for other products -->
        </div>
    </div>
</div>





{% endblock body %}